apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: '2018-05-06 13:14:49 +0000 UTC'
    openshift.io/deployer-pod.created-at: '2018-05-06 13:14:29 +0000 UTC'
    openshift.io/deployer-pod.name: wordpress-mysql-1-deploy
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: wordpress-mysql
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: '1'
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"wordpress-mysql","namespace":"lb3-wordpress","selfLink":"/apis/apps.openshift.io/v1/namespaces/lb3-wordpress/deploymentconfigs/wordpress-mysql","uid":"67aed9a8-512f-11e8-b302-96be9e034501","resourceVersion":"1841","generation":2,"creationTimestamp":"2018-05-06T13:14:27Z","labels":{"app":"mysql-persistent","template":"mysql-persistent-template"},"annotations":{"template.alpha.openshift.io/wait-for-ready":"true"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["mysql"],"from":{"kind":"ImageStreamTag","namespace":"openshift","name":"mysql:5.7"},"lastTriggeredImage":"docker.io/centos/mysql-57-centos7@sha256:6b51e4675da73f1af4e72432149c42464ba0f685f5bdf68f05459c0e25e2592e"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"wordpress-mysql"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"wordpress-mysql"}},"spec":{"volumes":[{"name":"wordpress-mysql-data","persistentVolumeClaim":{"claimName":"wordpress-mysql"}}],"containers":[{"name":"mysql","image":"docker.io/centos/mysql-57-centos7@sha256:6b51e4675da73f1af4e72432149c42464ba0f685f5bdf68f05459c0e25e2592e","ports":[{"containerPort":3306,"protocol":"TCP"}],"env":[{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"name":"wordpress-mysql","key":"database-user"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"name":"wordpress-mysql","key":"database-password"}}},{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"name":"wordpress-mysql","key":"database-root-password"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"name":"wordpress-mysql","key":"database-name"}}}],"resources":{"limits":{"memory":"512Mi"}},"volumeMounts":[{"name":"wordpress-mysql-data","mountPath":"/var/lib/mysql/data"}],"livenessProbe":{"tcpSocket":{"port":3306},"initialDelaySeconds":30,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"exec":{"command":["/bin/sh","-i","-c","MYSQL_PWD=\"$MYSQL_PASSWORD\"
      mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT
      1'"]},"initialDelaySeconds":5,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config
      change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-05-06T13:14:27Z","lastTransitionTime":"2018-05-06T13:14:27Z","message":"Deployment
      config does not have minimum availability."}]}}
  creationTimestamp: '2018-05-06T13:14:29Z'
  generation: 2
  labels:
    app: mysql-persistent
    openshift.io/deployment-config.name: wordpress-mysql
    template: mysql-persistent-template
  name: wordpress-mysql-1
  namespace: lb3-wordpress
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: wordpress-mysql
      uid: 67aed9a8-512f-11e8-b302-96be9e034501
  resourceVersion: '1908'
  selfLink: /api/v1/namespaces/lb3-wordpress/replicationcontrollers/wordpress-mysql-1
  uid: 68509a36-512f-11e8-b302-96be9e034501
spec:
  replicas: 1
  selector:
    deployment: wordpress-mysql-1
    deploymentconfig: wordpress-mysql
    name: wordpress-mysql
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: '1'
        openshift.io/deployment-config.name: wordpress-mysql
        openshift.io/deployment.name: wordpress-mysql-1
      creationTimestamp: null
      labels:
        deployment: wordpress-mysql-1
        deploymentconfig: wordpress-mysql
        name: wordpress-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: wordpress-mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: wordpress-mysql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: wordpress-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: wordpress-mysql
          image: >-
            docker.io/centos/mysql-57-centos7@sha256:6b51e4675da73f1af4e72432149c42464ba0f685f5bdf68f05459c0e25e2592e
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: wordpress-mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: wordpress-mysql-data
          persistentVolumeClaim:
            claimName: wordpress-mysql
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1

